export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.cargo/bin"
cdl() {
  if [ ! -z "$@" ]
  then
    DIR="$@"
  else
    DIR="`pwd`"
  fi
  cd "$DIR" && pwd && ls -la
}
if which rbenv > /dev/null; then
  export PATH="$PATH:$HOME/.rbenv/bin"
  eval "$(rbenv init -)"
fi
stty -ixon
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
