export PATH="$PATH:$HOME/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.rbenv/bin"
if which rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi
export PATH="$PATH:$HOME/.nodenv/bin"
if which nodenv > /dev/null; then
  eval "$(nodenv init -)"
fi

cdl() {
  if [ ! -z "$@" ]
  then
    DIR="$@"
  else
    DIR="`pwd`"
  fi
  cd "$DIR" && pwd && ls -la
}

stty -ixon
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi
